/* Rivieraen 2026 — designsystem «Azure & Earth» (French Riviera Planner, Stitch).
   Settes ETTER Tailwind Play-CDN-taggen så konfigen ligger ett sted for alle sider. */
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#2f1500",
        "secondary-container": "#a3d4ff",
        "on-primary-fixed-variant": "#6e3900",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#fdeade",
        "primary-container": "#b15f00",
        "inverse-primary": "#ffb77d",
        "secondary-fixed": "#cbe6ff",
        "sand": "#F5F5F4",
        "terracotta": "#B45309",
        "outline": "#887364",
        "background": "#fff8f5",
        "outline-variant": "#dbc2b0",
        "primary-fixed-dim": "#ffb77d",
        "tertiary-fixed-dim": "#dcc66e",
        "tertiary-fixed": "#f9e287",
        "on-tertiary-fixed": "#221b00",
        "azure": "#0EA5E9",
        "surface-container-low": "#fff1e9",
        "on-tertiary-container": "#4b3f00",
        "on-tertiary-fixed-variant": "#534600",
        "surface-container-highest": "#f2dfd3",
        "primary-fixed": "#ffdcc3",
        "inverse-surface": "#392e26",
        "surface-bright": "#fff8f5",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#001e30",
        "on-secondary": "#ffffff",
        "tertiary": "#6e5e0d",
        "on-primary": "#ffffff",
        "primary": "#8d4b00",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "surface-dim": "#e9d7cb",
        "on-secondary-container": "#275c81",
        "surface": "#fff8f5",
        "on-surface": "#231a13",
        "secondary": "#2f6388",
        "inverse-on-surface": "#ffede3",
        "on-surface-variant": "#554336",
        "on-background": "#231a13",
        "surface-variant": "#f2dfd3",
        "on-error": "#ffffff",
        "surface-tint": "#904d00",
        "error": "#ba1a1a",
        "on-primary-container": "#fffbff",
        "secondary-fixed-dim": "#9bccf6",
        "surface-container-high": "#f7e5d9",
        "on-secondary-fixed-variant": "#0e4b6f",
        "tertiary-container": "#bfab56",
        "ivory": "#FAF9F6"
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
      spacing: { "gutter": "16px", "container-max": "1200px", "margin-mobile": "20px", "margin-desktop": "64px", "unit": "8px" },
      fontFamily: {
        "headline-md": ["Libre Caslon Text", "Georgia", "serif"],
        "label-md": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Libre Caslon Text", "Georgia", "serif"],
        "display-lg": ["Libre Caslon Text", "Georgia", "serif"],
        "headline-lg": ["Libre Caslon Text", "Georgia", "serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "700" }]
      }
    }
  }
};
